### ISSUE TITLE
add missing dependencies

### ISSUE THREAD

**Issue by jwildfire** [SafetyGraphics/safetyCharts#30]
As noted, in [this safetyGraphics issue](https://github.com/SafetyGraphics/safetyGraphics/issues/450), there are several dependencies that are not accounted for in safetyCharts. Need to resolve this before v1 release.

**Comment by samussiah** [comment]
`Tplyr` and `kableExtra` still require manual inclusion prior to calling `safetyGraphicsApp()` - not sure how to address this.

**Comment by xni7** [comment]
@samussiah , @jwildfire , just pushed a new commit cb51e2b that should have resolved the `Tplyr` and `kableExtra` pkg dependency issues. 

- For `kableExtra` the problem is NAMESPACE was missing the `import(Tplyr)` entry.  I moved the location `inst/config/workflow/tplyr_shift_chart.R → R/tplyr_shift_chart.R `, so that `devtools::document()` can pick up and import `kableExtra` in NAMESPACE. `Tplyr` was already imported through other functions under `R/`
- `Tplyr` is more complicated. First, there is a typo in "pacakage". Secondly the `safetyGraphics` [makeChartConfig.R Line 72](https://github.com/SafetyGraphics/safetyGraphics/blob/b0623f4b78399999d4ac8964741f0883c8ea5e38/R/makeChartConfig.R#L72) seems to expect the package to be attached in the search path. So that's probably why you need to do the `library()` calls first. I changed it to `safetyCharts` because most likely it should be attached first. 

My other thought is about the `init` function location. If we load the custom configs from a user custom folder, the init function is probably co-located with the yaml file. It might be counter-intuitive in the `safetyCharts` examples to separate the init function with yaml into two folder under R/ and inst/config/.
