### ISSUE TITLE
tpylr shift table isn't rendering

### ISSUE THREAD

**Issue by jwildfire** [SafetyGraphics/safetyCharts#50]
This chart was really just a proof of concept, so I'm leaning towards just removing this from v1 unless @elimillera or @MayaGans wants to poke around and make some improvements. Getting 'Error: could not find function "scroll_box"'. YAML [here](https://github.com/SafetyGraphics/safetyCharts/blob/dev/inst/config/tplyr_shift.yaml) and code [here](https://github.com/SafetyGraphics/safetyCharts/blob/dev/inst/config/workflow/tplyr_shift_chart.R).

**Comment by elimillera** [comment]
Hey Jeremy,

I was able to get this to load by loading in 'kableExtra' and 'Tplyr'. I'm thinking this is because the tplyr_shift is listed under the package "Tplyr" whereas the tplyr_demog is under the safetyCharts package. I should be able to get a timeline in for including something in Tplyr in the inst folder so we can make them talk to each other, but I'm not able to give a timeline or anything.

Eli
